# Arrays
* pip install array 
## typing conda prompt


In [1]:
import array as ar

In [2]:
a=ar.array('i',[1,2,3,4,5])
b=ar.array('i',[6,7,8,9,10])

In [3]:
a

array('i', [1, 2, 3, 4, 5])

In [4]:
b

array('i', [6, 7, 8, 9, 10])

In [5]:
len(b)

5

In [6]:
a[::1]

array('i', [1, 2, 3, 4, 5])

In [7]:
#reversing
b[::-1]

array('i', [10, 9, 8, 7, 6])

In [8]:
a+b

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [9]:
a

array('i', [1, 2, 3, 4, 5])

In [10]:
a.append(0)

In [11]:
a

array('i', [1, 2, 3, 4, 5, 0])

In [12]:
a.pop(5)

0

In [13]:
a

array('i', [1, 2, 3, 4, 5])

In [14]:
for i in a:print(i)

1
2
3
4
5


# NUMPY
pip3 install numpy

In [15]:
import numpy as np

In [18]:
x=np.array([(1,2,3,4),(9,8,7,6)])
y=np.array([(4,5,3,6),(9,5,8,3)])
a

array('i', [1, 2, 3, 4, 5])

In [19]:
x,y

(array([[1, 2, 3, 4],
        [9, 8, 7, 6]]),
 array([[4, 5, 3, 6],
        [9, 5, 8, 3]]))

In [57]:
y.ndim 

2

In [21]:
x.ndim

2

In [22]:
x.size

8

In [23]:
y.size

8

In [24]:
y.shape

(2, 4)

In [26]:
y.reshape(4,2)

array([[4, 5],
       [3, 6],
       [9, 5],
       [8, 3]])

In [31]:
a=np.linspace(1,9,10)
a

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [32]:
x.max()

9

In [33]:
x.min()

1

In [34]:
x

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [35]:
x[1:3]

array([[9, 8, 7, 6]])

In [36]:
x[x>2]

array([3, 4, 9, 8, 7, 6])

In [38]:
x[x<5]

array([1, 2, 3, 4])

In [39]:
x[x==5]

array([], dtype=int32)

In [42]:
x+y

array([[4, 5, 3, 6],
       [9, 5, 8, 3]])

In [48]:
f=np.random.randint(5,size=7)
f

array([3, 0, 2, 3, 4, 2, 2])